### ISSUE TITLE
Image Ordering

### ISSUE THREAD

**Issue by atilkan** [mbuczko/jQuery-Sliding-Carousel#3]
Image ordering works according to loaded order. Html ordering doesn't work.
When all loaded, ordering should be set again.

**Comment by mbuczko** [comment]
hopefully fixed.

**Comment by atilkan** [comment]
You are fast. Thanks. This is one of the best accordion. Shame people did not notice it yet.

**Comment by mbuczko** [comment]
Thanks! Hopefully swipe gestures will make it more popular. This is actually thing I miss the most trying to integrate this carousel into responsive web app. So, I'm eagerly waiting for your pull request :)
