### ISSUE TITLE
Multiple Slider in one page, Arrow problem.

### ISSUE THREAD

**Issue by atilkan** [mbuczko/jQuery-Sliding-Carousel#4]
Arrows doesn't work cause they have ids. To correct it, they should have classes.

Inside setup event, arrow selector should be like this. I tried, it is working but not sure if it is the best way.
pluginData.container.closest('.carousel-container').find('.carousel-left').click();
instead of 
$('#carousel-left').click();

**Comment by mbuczko** [comment]
ok, fixed that one as well. I have also simplified html markup/css-es and js code a bit.

**Comment by atilkan** [comment]
Nice Job. Sorry i did not mention, one thing is missing. #carousel can also cause problem. I didn't test it though.
